version: "3.8"
services:
  mc_frosthold:
    image: itzg/minecraft-server
    container_name: frosthold
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
      MEMORY: "10G"
      VERSION: "LATEST"
      LEVEL_NAME: "world"
    volumes:
      - ./data:/data
      - ./logs:/logs
    restart: unless-stopped

