global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'minecraft-monitor'

scrape_configs:
  - job_name: 'minecraft-exporter'
    static_configs:
      - targets: ['minecraft-exporter:9225']
        labels:
          instance: 'minecraft-server'

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
